version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "botless-review-required"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"